### ISSUE TITLE
Fix "Stores" tab

### ISSUE THREAD

**Issue by rafalcymerys** [spree/spree_backend#176]
On the latest branch, when accessing Configuration -> Stores, we get an error.

**Comment by adrianryt** [comment]
This is related to this PR: https://github.com/spree/spree_backend/commit/e1f390e6eeb4f5f6c09fc4d8a679305118213c12

**Comment by rafalcymerys** [comment]
There are two issues that we can see from the UX perspective:
1. It's not obvious that the user can click on the store name on the left side of the top bar - we should discuss what's the correct UX for that, given that clicking on it allows the admin to change store or to create a new store
2. Breadcrumbs on the /admin/stores/new page, shouldn't contain a link to /admin/stores page, as it's now not available
